[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[options]
include_package_data = true
package_dir = {"" = "src"}
packages = ["uw_chess"]

[project]
name = "uw_chess"
version = "0.1.0b1"
description = "Practice playing blindfold chess"
requires-python = ">=3.9"
license = {file = "LICENSE"}
urls = {source = "https://github.com/kfmh/uw-chess"}

dependencies = [
    "rich==13.7.0",
    "tqdm==4.66.1",
]

[project.scripts]
uw_chess = "uw_chess.main:main_wrapper"
